#!/usr/bin/env python3

import requests
import sys

URL = "http://zap.sermaistecnologia.com.br/api/message"
PHONE = sys.argv[1]
TITULO = sys.argv[2]
MESSAGE = (TITULO + sys.argv[3]).replace("\\n", "\n")

data = {
    "number": PHONE,
    "message": MESSAGE
}

headers = {
    "Content-Type": "application/json"
}

response = requests.post(URL, json=data, headers=headers)

print(response.text)
